### ISSUE TITLE
can't find function 'tbl' - clarify dplyr/tidyverse dependency in vignettes

### ISSUE THREAD

**Issue by rcorty** [roux-ohdsi/allofus#25]
going through the getting started example and hit this bug pretty early on...will do some trouble shooting but wanted to make developers aware

<img width="904" alt="image" src="https://github.com/user-attachments/assets/ab753bdb-e1f1-44fc-bf59-717527e44835">

maybe package depends on env variables that are only present in rstudio environment?

**Comment by rcorty** [comment]
just needed to add library(dplyr)

**Comment by rbcavanaugh** [comment]
Thanks @rcorty - you're right that slipped through the cracks in the vignette. We don't explicitly depend on dplyr since it's a heavy dependency, but it is required to use much of the package.
