### ISSUE TITLE
aou_connect fails to connect with no helpful error message

### ISSUE THREAD

**Issue by louisahsmith** [roux-ohdsi/allofus#6]
Relevant packages from `aou_session_info()`:

package | ondiskversion | loadedversion | path | loadedpath | attached | is_base | date | source | md5ok | library
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
bigrquery | bigrquery | 1.4.2 | 1.4.2 | /home/jupyter/packages/bigrquery | /home/jupyter/packages/bigrquery | FALSE | FALSE | 2023-04-20 | CRAN (R 4.3.1) | NA | /home/jupyter/packages
dbplyr | dbplyr | 2.4.0.9000 | 2.4.0.9000 | /home/jupyter/packages/dbplyr | /home/jupyter/packages/dbplyr | FALSE | FALSE | 2024-01-09 | Github (tidyverse/dbplyr@a40c03a91852e93c2cae8a0bcbf4e421a751780d) | NA | /home/jupyter/packages
dplyr | dplyr | 1.1.4 | 1.1.4 | /home/jupyter/packages/dplyr | /home/jupyter/packages/dplyr | TRUE | FALSE | 2023-11-17 | CRAN (R 4.3.1) | NA | /home/jupyter/packages

Error text:
```
Error:
! Unable to connect to CDR fc-aou-cdr-prod-ct.C2022Q4R11
Traceback:

1. aou_connect()
2. tryCatch({
 .     dataset <- strsplit(CDR, split = "\\.")[[1]]
 .     release <- dataset[2]
 .     prefix <- dataset[1]
 .     connection <- DBI::dbConnect(bigrquery::bigquery(), billing = Sys.getenv("GOOGLE_PROJECT"), 
 .         project = prefix, dataset = release, bigint = "integer64", 
 .         ...)
 .     if (is.na(connection@dataset) | connection@dataset != release) {
 .         stop()
 .     }
 .     test_table <- dplyr::tbl(connection, "person")
 .     cli::cli_inform(c(v = "Connected successfully!"))
 .     options(aou.default.con = connection)
 .     connection
 . }, error = function(e) {
 .     cli::cli_abort(c("Unable to connect to CDR {CDR}"), call = NULL)
 .     return(e)
 . })
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. value[[3L]](cond)
6. cli::cli_abort(c("Unable to connect to CDR {CDR}"), call = NULL)
7. rlang::abort(message, ..., call = call, use_cli_format = TRUE, 
 .     .frame = .frame)
8. signal_abort(cnd, .file)
```

**Comment by louisahsmith** [comment]
Putting this here as another example of package version incompatibility. 
On a fresh rstudio session with no package installations but pak and allofus, getting no error in the connection `Error in strsplit(name, ".", fixed = TRUE) : non-character argument` with

bigrquery     1.4.1      
dbplyr        2.3.2   
 dplyr       * 1.1.1

**Comment by louisahsmith** [comment]
More notes:
Connection error with dev version of dbplyr, dplyr
But with dev version of bigrquery as well, everything works!

**Comment by rbcavanaugh** [comment]
I think we should require dbplyr 2.5.0 > greater (on CRAN currently) and bigrquery > 1.5.1 (on CRAN currently). Seems to work ok with these two packages and avoids the strsplit error entirely
